apiVersion: v1
kind: PersistentVolume
metadata:
  name: simple-admin-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-admin-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

