version: '3'

volumes:
  postgresql:
  redis:

networks:
  simple-admin:
    driver: bridge

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: always
    ports:
      - '5432:5432'
    environment:
      MYSQL_DATABASE: 'simple_admin'
      POSTGRESQL_PASSWORD: '123456'
    volumes:
      - 'postgresql:/bitnami/postgresql'
    networks:
      simple-admin:
        aliases:
          - postgresqlserver
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1000M
        reservations:
          cpus: '0.05'
          memory: 200M

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    networks:
      simple-admin:
        aliases:
          - redisserver
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.05'
          memory: 200M
