// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	ent2 "github.com/suyuan32/simple-admin-core/service/admin/rpc/ent"
	"github.com/suyuan32/simple-admin-core/service/admin/rpc/ent/api"
	"github.com/suyuan32/simple-admin-core/service/admin/rpc/ent/configuration"
	"github.com/suyuan32/simple-admin-core/service/admin/rpc/ent/department"
	"github.com/suyuan32/simple-admin-core/service/admin/rpc/ent/dictionary"
	"github.com/suyuan32/simple-admin-core/service/admin/rpc/ent/dictionarydetail"
	"github.com/suyuan32/simple-admin-core/service/admin/rpc/ent/menu"
	"github.com/suyuan32/simple-admin-core/service/admin/rpc/ent/oauthprovider"
	"github.com/suyuan32/simple-admin-core/service/admin/rpc/ent/position"
	"github.com/suyuan32/simple-admin-core/service/admin/rpc/ent/predicate"
	"github.com/suyuan32/simple-admin-core/service/admin/rpc/ent/role"
	"github.com/suyuan32/simple-admin-core/service/admin/rpc/ent/token"
	"github.com/suyuan32/simple-admin-core/service/admin/rpc/ent/user"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next ent2.Querier) ent2.Querier {
	return ent2.QuerierFunc(func(ctx context.Context, q ent2.Query) (ent2.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next ent2.Querier) ent2.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q ent2.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The APIFunc type is an adapter to allow the use of ordinary function as a Querier.
type APIFunc func(context.Context, *ent2.APIQuery) (ent2.Value, error)

// Query calls f(ctx, q).
func (f APIFunc) Query(ctx context.Context, q ent2.Query) (ent2.Value, error) {
	if q, ok := q.(*ent2.APIQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.APIQuery", q)
}

// The TraverseAPI type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAPI func(context.Context, *ent2.APIQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAPI) Intercept(next ent2.Querier) ent2.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAPI) Traverse(ctx context.Context, q ent2.Query) error {
	if q, ok := q.(*ent2.APIQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.APIQuery", q)
}

// The ConfigurationFunc type is an adapter to allow the use of ordinary function as a Querier.
type ConfigurationFunc func(context.Context, *ent2.ConfigurationQuery) (ent2.Value, error)

// Query calls f(ctx, q).
func (f ConfigurationFunc) Query(ctx context.Context, q ent2.Query) (ent2.Value, error) {
	if q, ok := q.(*ent2.ConfigurationQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ConfigurationQuery", q)
}

// The TraverseConfiguration type is an adapter to allow the use of ordinary function as Traverser.
type TraverseConfiguration func(context.Context, *ent2.ConfigurationQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseConfiguration) Intercept(next ent2.Querier) ent2.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseConfiguration) Traverse(ctx context.Context, q ent2.Query) error {
	if q, ok := q.(*ent2.ConfigurationQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ConfigurationQuery", q)
}

// The DepartmentFunc type is an adapter to allow the use of ordinary function as a Querier.
type DepartmentFunc func(context.Context, *ent2.DepartmentQuery) (ent2.Value, error)

// Query calls f(ctx, q).
func (f DepartmentFunc) Query(ctx context.Context, q ent2.Query) (ent2.Value, error) {
	if q, ok := q.(*ent2.DepartmentQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.DepartmentQuery", q)
}

// The TraverseDepartment type is an adapter to allow the use of ordinary function as Traverser.
type TraverseDepartment func(context.Context, *ent2.DepartmentQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseDepartment) Intercept(next ent2.Querier) ent2.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseDepartment) Traverse(ctx context.Context, q ent2.Query) error {
	if q, ok := q.(*ent2.DepartmentQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.DepartmentQuery", q)
}

// The DictionaryFunc type is an adapter to allow the use of ordinary function as a Querier.
type DictionaryFunc func(context.Context, *ent2.DictionaryQuery) (ent2.Value, error)

// Query calls f(ctx, q).
func (f DictionaryFunc) Query(ctx context.Context, q ent2.Query) (ent2.Value, error) {
	if q, ok := q.(*ent2.DictionaryQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.DictionaryQuery", q)
}

// The TraverseDictionary type is an adapter to allow the use of ordinary function as Traverser.
type TraverseDictionary func(context.Context, *ent2.DictionaryQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseDictionary) Intercept(next ent2.Querier) ent2.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseDictionary) Traverse(ctx context.Context, q ent2.Query) error {
	if q, ok := q.(*ent2.DictionaryQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.DictionaryQuery", q)
}

// The DictionaryDetailFunc type is an adapter to allow the use of ordinary function as a Querier.
type DictionaryDetailFunc func(context.Context, *ent2.DictionaryDetailQuery) (ent2.Value, error)

// Query calls f(ctx, q).
func (f DictionaryDetailFunc) Query(ctx context.Context, q ent2.Query) (ent2.Value, error) {
	if q, ok := q.(*ent2.DictionaryDetailQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.DictionaryDetailQuery", q)
}

// The TraverseDictionaryDetail type is an adapter to allow the use of ordinary function as Traverser.
type TraverseDictionaryDetail func(context.Context, *ent2.DictionaryDetailQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseDictionaryDetail) Intercept(next ent2.Querier) ent2.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseDictionaryDetail) Traverse(ctx context.Context, q ent2.Query) error {
	if q, ok := q.(*ent2.DictionaryDetailQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.DictionaryDetailQuery", q)
}

// The MenuFunc type is an adapter to allow the use of ordinary function as a Querier.
type MenuFunc func(context.Context, *ent2.MenuQuery) (ent2.Value, error)

// Query calls f(ctx, q).
func (f MenuFunc) Query(ctx context.Context, q ent2.Query) (ent2.Value, error) {
	if q, ok := q.(*ent2.MenuQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.MenuQuery", q)
}

// The TraverseMenu type is an adapter to allow the use of ordinary function as Traverser.
type TraverseMenu func(context.Context, *ent2.MenuQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseMenu) Intercept(next ent2.Querier) ent2.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseMenu) Traverse(ctx context.Context, q ent2.Query) error {
	if q, ok := q.(*ent2.MenuQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.MenuQuery", q)
}

// The OauthProviderFunc type is an adapter to allow the use of ordinary function as a Querier.
type OauthProviderFunc func(context.Context, *ent2.OauthProviderQuery) (ent2.Value, error)

// Query calls f(ctx, q).
func (f OauthProviderFunc) Query(ctx context.Context, q ent2.Query) (ent2.Value, error) {
	if q, ok := q.(*ent2.OauthProviderQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OauthProviderQuery", q)
}

// The TraverseOauthProvider type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOauthProvider func(context.Context, *ent2.OauthProviderQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOauthProvider) Intercept(next ent2.Querier) ent2.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOauthProvider) Traverse(ctx context.Context, q ent2.Query) error {
	if q, ok := q.(*ent2.OauthProviderQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OauthProviderQuery", q)
}

// The PositionFunc type is an adapter to allow the use of ordinary function as a Querier.
type PositionFunc func(context.Context, *ent2.PositionQuery) (ent2.Value, error)

// Query calls f(ctx, q).
func (f PositionFunc) Query(ctx context.Context, q ent2.Query) (ent2.Value, error) {
	if q, ok := q.(*ent2.PositionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PositionQuery", q)
}

// The TraversePosition type is an adapter to allow the use of ordinary function as Traverser.
type TraversePosition func(context.Context, *ent2.PositionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePosition) Intercept(next ent2.Querier) ent2.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePosition) Traverse(ctx context.Context, q ent2.Query) error {
	if q, ok := q.(*ent2.PositionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PositionQuery", q)
}

// The RoleFunc type is an adapter to allow the use of ordinary function as a Querier.
type RoleFunc func(context.Context, *ent2.RoleQuery) (ent2.Value, error)

// Query calls f(ctx, q).
func (f RoleFunc) Query(ctx context.Context, q ent2.Query) (ent2.Value, error) {
	if q, ok := q.(*ent2.RoleQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RoleQuery", q)
}

// The TraverseRole type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRole func(context.Context, *ent2.RoleQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRole) Intercept(next ent2.Querier) ent2.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRole) Traverse(ctx context.Context, q ent2.Query) error {
	if q, ok := q.(*ent2.RoleQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RoleQuery", q)
}

// The TokenFunc type is an adapter to allow the use of ordinary function as a Querier.
type TokenFunc func(context.Context, *ent2.TokenQuery) (ent2.Value, error)

// Query calls f(ctx, q).
func (f TokenFunc) Query(ctx context.Context, q ent2.Query) (ent2.Value, error) {
	if q, ok := q.(*ent2.TokenQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.TokenQuery", q)
}

// The TraverseToken type is an adapter to allow the use of ordinary function as Traverser.
type TraverseToken func(context.Context, *ent2.TokenQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseToken) Intercept(next ent2.Querier) ent2.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseToken) Traverse(ctx context.Context, q ent2.Query) error {
	if q, ok := q.(*ent2.TokenQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.TokenQuery", q)
}

// The UserFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserFunc func(context.Context, *ent2.UserQuery) (ent2.Value, error)

// Query calls f(ctx, q).
func (f UserFunc) Query(ctx context.Context, q ent2.Query) (ent2.Value, error) {
	if q, ok := q.(*ent2.UserQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// The TraverseUser type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUser func(context.Context, *ent2.UserQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUser) Intercept(next ent2.Querier) ent2.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUser) Traverse(ctx context.Context, q ent2.Query) error {
	if q, ok := q.(*ent2.UserQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q ent2.Query) (Query, error) {
	switch q := q.(type) {
	case *ent2.APIQuery:
		return &query[*ent2.APIQuery, predicate.API, api.OrderOption]{typ: ent2.TypeAPI, tq: q}, nil
	case *ent2.ConfigurationQuery:
		return &query[*ent2.ConfigurationQuery, predicate.Configuration, configuration.OrderOption]{typ: ent2.TypeConfiguration, tq: q}, nil
	case *ent2.DepartmentQuery:
		return &query[*ent2.DepartmentQuery, predicate.Department, department.OrderOption]{typ: ent2.TypeDepartment, tq: q}, nil
	case *ent2.DictionaryQuery:
		return &query[*ent2.DictionaryQuery, predicate.Dictionary, dictionary.OrderOption]{typ: ent2.TypeDictionary, tq: q}, nil
	case *ent2.DictionaryDetailQuery:
		return &query[*ent2.DictionaryDetailQuery, predicate.DictionaryDetail, dictionarydetail.OrderOption]{typ: ent2.TypeDictionaryDetail, tq: q}, nil
	case *ent2.MenuQuery:
		return &query[*ent2.MenuQuery, predicate.Menu, menu.OrderOption]{typ: ent2.TypeMenu, tq: q}, nil
	case *ent2.OauthProviderQuery:
		return &query[*ent2.OauthProviderQuery, predicate.OauthProvider, oauthprovider.OrderOption]{typ: ent2.TypeOauthProvider, tq: q}, nil
	case *ent2.PositionQuery:
		return &query[*ent2.PositionQuery, predicate.Position, position.OrderOption]{typ: ent2.TypePosition, tq: q}, nil
	case *ent2.RoleQuery:
		return &query[*ent2.RoleQuery, predicate.Role, role.OrderOption]{typ: ent2.TypeRole, tq: q}, nil
	case *ent2.TokenQuery:
		return &query[*ent2.TokenQuery, predicate.Token, token.OrderOption]{typ: ent2.TypeToken, tq: q}, nil
	case *ent2.UserQuery:
		return &query[*ent2.UserQuery, predicate.User, user.OrderOption]{typ: ent2.TypeUser, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
